name: Combine API dan UI Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # 1. Job untuk API Testing
  api-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install API test dependencies
      run: |
        pip install pytest requests pytest-html

    - name: Run API tests
      run: |
        pytest tests/api/ --html=api-report.html --self-contained-html

    - name: Upload API test report
      uses: actions/upload-artifact@v4
      with:
        name: api-test-report
        path: api-report.html

  # 2. Job untuk Web UI Testing
  automation-junit:
    needs: api-test  # Menunggu API test selesai (opsional)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Setup gradlew
      run: chmod +x gradlew

    - name: Execute Cucumber Tests
      run: ./gradlew cucumber
      
    - name: Archive test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: cucumber-reports
        path: reports

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.Cth }}
        publish_dir: ./reports
        force_orphan: true
        keep_files: false
