name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  automation-Junit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
   
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v0.0.0

    - name: Setup gradlew
      run: chmod +x gradlew

    - name: Execute Cucumber Tests
      run: ./gradlew cucumber
      
    - name: Archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: reports

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.Cth }}
        publish_dir: ./reports
        force_orphan: true
        keep_files: false

