name: Web Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

Permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  automation-Junit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: false

    - name: Build with Gradle
      run:
       chmod +x gradlew
       ./gradlew build

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.4.0
      with:
        chrome-version: 'latest'

    - name: Execute Cucumber Tests
      run: ./gradlew clean test
      env:
        HEADLESS_MODE: true

    - name: Archive test results
      uses: actions/upload-artifact@v4.3.0
      if: always()
      with:
        name: cucumber reports
        path: target/cucumber-reports.html

